name: mywine
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+1620000002

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  firebase_core: ^1.6.0
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.1.0
  provider: ^6.0.0
  get_it: ^7.2.0
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2
  build_runner: ^2.1.2
  sqflite: ^2.0.0+4
  sqlbrite: ^2.2.0
  fuzzy: ^0.4.0-nullsafety.0
  animate_icons: ^2.0.0
  draggable_scrollbar: ^0.1.0
  flutter_svg: ^0.23.0+1
  camerawesome: ^0.3.0+1
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.6
  flutter_image_compress: ^1.1.0
  loading_indicator: ^3.0.2
  flutter_spinbox: ^0.6.0
  modal_bottom_sheet: ^2.0.0
  googleapis: ^7.0.0
  googleapis_auth: ^1.2.0
  string_similarity: ^2.0.0
  google_sign_in: ^5.2.1
  permission_handler: ^8.2.5
  uuid: ^3.0.5
  flutter_keyboard_visibility: ^5.1.0
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/credentials/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
